name: Build and push docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: check out code
      uses: actions/checkout@v4

    - 
      name: Extract metadata (tags, labels) for Docker
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: supermalang/xaymaappcron
        labels: |
          org.opencontainers.image.title=xaymash-app-cron
          org.opencontainers.image.description=A cron container image to easily run cron jobs for the Xayma.sh web app platform
          org.opencontainers.image.vendor=XAYMA Labs
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern=0
          type=semver,pattern=1.1
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    - 
      name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}  

    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }} # if event is push (alternative to : `push: true`)
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
